<a href="https://colab.research.google.com/github/Ayush-ds-phy/Pytorch_yt/blob/main/Pytorch_Tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np
tensor1 = torch.randn(3,4,2)
print(tensor1)

tensor([[[-1.4674,  1.4821],
         [ 0.6227,  1.3936],
         [-0.1580, -1.5941],
         [-0.4723, -0.5156]],

        [[ 0.1856, -0.3944],
         [-0.3386, -1.5044],
         [-1.2153, -0.5922],
         [-0.5648,  1.7155]],

        [[-0.3949, -1.4338],
         [-0.3678,  0.3709],
         [-2.3976, -1.3038],
         [ 0.1094, -1.0479]]])


In [7]:
#reshape
my= torch.arange(10)
myreshape= my.reshape(2,5)
myreshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
#view
myv= my.view(2,5)
myv

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
#Slicer
my2= my.reshape(5,2)
print(my2)
my1=my2[:,1:]
my1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [14]:
my= torch.arange(10)
print(my)
s=my[7]
print(s)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(7)


In [17]:
#addition
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,2,4,1])
print(tensor_a+tensor_b)
torch.add(tensor_a,tensor_b)

tensor([4, 4, 7, 5])


tensor([4, 4, 7, 5])

In [18]:
#subtraction
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,2,4,1])
print(tensor_a-tensor_b)
torch.sub(tensor_a,tensor_b)

tensor([-2,  0, -1,  3])


tensor([-2,  0, -1,  3])

In [19]:
#multiplication
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,2,4,1])
print(tensor_a*tensor_b)
torch.mul(tensor_a,tensor_b)

tensor([ 3,  4, 12,  4])


tensor([ 3,  4, 12,  4])

In [20]:
#Division
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,2,4,1])
print(tensor_a/tensor_b)
torch.div(tensor_a,tensor_b)

tensor([0.3333, 1.0000, 0.7500, 4.0000])


tensor([0.3333, 1.0000, 0.7500, 4.0000])

In [22]:
#remainder
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,2,4,1])
print(tensor_a%tensor_b)
torch.remainder(tensor_a,tensor_b)

tensor([1, 0, 3, 0])


tensor([1, 0, 3, 0])

In [24]:
#exponents/pow
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,2,4,1])
torch.pow(tensor_a,tensor_b)

tensor([ 1,  4, 81,  4])

In [28]:
#reassignment
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([3,2,4,1])
print(tensor_a+tensor_b)
print(tensor_a.add_(tensor_b))
print(tensor_a)

tensor([4, 4, 7, 5])
tensor([4, 4, 7, 5])
tensor([4, 4, 7, 5])
